<?php

/**
 * @file
 * Contains ctu_comments.module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ctu_comments_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ctu_comments module.
    case 'help.page.ctu_comments':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Comment Functionality') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 *
 * @param array $build
 * @param \Drupal\Core\Entity\EntityInterface $entity
 * @param \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display
 * @param $view_mode
 */
function ctu_comments_comment_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  $params = [
    'method' => 'nojs',
    'comment' => $entity->id(),
  ];

  $options = [
    'attributes' => [
      'class' => [
        'use-ajax',
        'ctu-comment-event-link',
      ],
    ],
  ];

  $build['read_more'] = \Drupal\Core\Link::createFromRoute('Read More', 'ctu_comments.ctu_comments_controller_comment_load', $params, $options)->toRenderable();
}
